apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - product-service.yaml
  - order-service.yaml
  - storefront.yaml
  - admin.yaml

labels:
  - pairs:
      part-of: apisix-sandbox
      layer: application
